function [loaded_config, surface_data] = load_session(filename, current_config)
%LOAD_SESSION Loads a session or simple data file.
%   Detects file type and loads accordingly. For simple files, it uses
%   variable name mapping from the current_config.

disp('--- Loading Session ---');

try
    data = load(filename);
catch ME
    error('Could not load or find the file: %s\nError: %s', filename, ME.message);
end

% Initialize outputs
loaded_config = [];
surface_data = struct();

% --- Check if this is a full session file generated by our tool ---
if isfield(data, 'session_data')
    disp(['  - Full session file detected. Unpacking...']);
    
    loaded_config = data.session_data.config;
    saved_surface = data.session_data.surface_data;
    
    surface_data.x_coords = saved_surface.x;
    surface_data.y_coords = saved_surface.y;
    surface_data.surface_h = saved_surface.f;
    surface_data.generation_params = saved_surface.generation_params;
    
else
    % --- Otherwise, treat as a simple .mat file with x, y, f data ---
    disp(['  - Simple .mat file detected. Mapping variables from config...']);
    
    % Get the variable names the user has specified in main_runner.m
    var_map = current_config.workflow.loadSimpleFile.varNames;
    
    % Check if the specified variables exist in the loaded file
    if ~isfield(data, var_map.x)
        error('Variable "%s" for x-coordinates not found in the file "%s". Check config.workflow.loadSimpleFile.varNames.', var_map.x, filename);
    end
    if ~isfield(data, var_map.y)
        error('Variable "%s" for y-coordinates not found in the file "%s". Check config.workflow.loadSimpleFile.varNames.', var_map.y, filename);
    end
    if ~isfield(data, var_map.f)
        error('Variable "%s" for height data not found in the file "%s". Check config.workflow.loadSimpleFile.varNames.', var_map.f, filename);
    end
    
    % Assign data using the mapped names
    surface_data.x_coords = data.(var_map.x);
    surface_data.y_coords = data.(var_map.y);
    surface_data.surface_h = data.(var_map.f);
end

% --- Final Validation and Grid Reconstruction ---
% Ensure coordinates are row vectors for consistency
if iscolumn(surface_data.x_coords); surface_data.x_coords = surface_data.x_coords'; end
if iscolumn(surface_data.y_coords); surface_data.y_coords = surface_data.y_coords'; end

% Validate dimensions
Nx = length(surface_data.x_coords);
Ny = length(surface_data.y_coords);
[mat_Ny, mat_Nx] = size(surface_data.surface_h);

assert(Nx == mat_Nx && Ny == mat_Ny, ...
    'Dimension mismatch between coordinate vectors and height matrix in loaded file.');

% Reconstruct the 2D grids needed by other functions
[surface_data.X_grid, surface_data.Y_grid] = meshgrid(surface_data.x_coords, surface_data.y_coords);

fprintf('Session successfully loaded from: %s\n', filename);

end